export const categories = [
  { value: 'youth', label: 'Youth' },
  { value: 'research', label: 'Research' },
  { value: 'scholarships', label: 'Scholarships' },
  { value: 'community', label: 'Community Development' },
  { value: 'education', label: 'Education' },
  { value: 'health', label: 'Health' },
  { value: 'environment', label: 'Environment' },
  { value: 'technology', label: 'Technology' },
  { value: 'arts', label: 'Arts & Culture' },
  { value: 'social_justice', label: 'Social Justice' },
  { value: 'climate', label: 'Climate Change' },
  { value: 'agriculture', label: 'Agriculture' },
  { value: 'food_security', label: 'Food Security' },
  { value: 'gender', label: 'Gender Equality' },
  { value: 'entrepreneurship', label: 'Entrepreneurship' },
  { value: 'startups', label: 'Startups' },
  { value: 'business', label: 'Business & Finance' },
  { value: 'sports', label: 'Sports' },
  { value: 'mental_health', label: 'Mental Health' },
  { value: 'innovation', label: 'Innovation' },
  { value: 'peacebuilding', label: 'Peacebuilding' },
  { value: 'civic_engagement', label: 'Civic Engagement' },
  { value: 'law', label: 'Law & Human Rights' },
  { value: 'journalism', label: 'Journalism & Media' },
  { value: 'philanthropy', label: 'Philanthropy' },
  { value: 'disability', label: 'Disability Inclusion' },
  { value: 'refugees', label: 'Refugees & Migration' },
  { value: 'water_sanitation', label: 'Water & Sanitation (WASH)' },
  { value: 'urban_development', label: 'Urban Development' },
  { value: 'rural_development', label: 'Rural Development' },
  { value: 'indigenous', label: 'Indigenous Peoples' },
  { value: 'wildlife', label: 'Wildlife Conservation' },
  { value: 'marine', label: 'Marine & Coastal Conservation' },
  { value: 'forestry', label: 'Forestry' },
  { value: 'energy', label: 'Renewable Energy' },
  { value: 'sustainability', label: 'Sustainable Development' },
  { value: 'infrastructure', label: 'Infrastructure' },
  { value: 'transport', label: 'Transport & Mobility' },
  { value: 'space', label: 'Space & Astronomy' },
  { value: 'ai', label: 'Artificial Intelligence (AI)' },
  { value: 'robotics', label: 'Robotics' },
  { value: 'data_science', label: 'Data Science' },
  { value: 'coding', label: 'Coding & Programming' },
  { value: 'digital_literacy', label: 'Digital Literacy' },
  { value: 'e_learning', label: 'E-learning' },
  { value: 'access_to_education', label: 'Access to Education' },
  { value: 'literacy', label: 'Literacy & Libraries' },
  { value: 'early_childhood', label: 'Early Childhood Development' },
  { value: 'stem', label: 'STEM (Science, Tech, Eng, Math)' },
  { value: 'human_rights', label: 'Human Rights' },
  { value: 'policy', label: 'Policy & Advocacy' },
  { value: 'leadership', label: 'Leadership' },
  { value: 'volunteering', label: 'Volunteering' },
  { value: 'internships', label: 'Internships & Fellowships' },
  { value: 'capacity_building', label: 'Capacity Building' },
  { value: 'grants', label: 'Grants & Funding' },
  { value: 'conflict_resolution', label: 'Conflict Resolution' },
  { value: 'democracy', label: 'Democracy & Governance' },
  { value: 'poverty', label: 'Poverty Alleviation' },
  { value: 'nonprofits', label: 'NGOs & Nonprofits' },
  { value: 'faith', label: 'Faith & Interreligious Dialogue' },
  { value: 'pandemics', label: 'Pandemic Response' },
  { value: 'epidemiology', label: 'Epidemiology & Infectious Diseases' },
  { value: 'rehabilitation', label: 'Rehabilitation & Disability' },
  { value: 'reproductive_health', label: 'Sexual & Reproductive Health' },
  { value: 'maternal_health', label: 'Maternal & Child Health' },
  { value: 'hiv', label: 'HIV/AIDS' },
  { value: 'drug_abuse', label: 'Drug Abuse & Prevention' },
  { value: 'public_health', label: 'Public Health' },
  { value: 'environmental_justice', label: 'Environmental Justice' },
  { value: 'oceans', label: 'Oceans & Blue Economy' },
  { value: 'waste', label: 'Waste Management' },
  { value: 'disaster_response', label: 'Disaster Response & Preparedness' },
  { value: 'emergency_relief', label: 'Emergency Relief' },
  { value: 'technology_for_good', label: 'Tech for Good' },
  { value: 'open_data', label: 'Open Data' },
  { value: 'youth_employment', label: 'Youth Employment' },
  { value: 'financial_literacy', label: 'Financial Literacy' },
  { value: 'rural_youth', label: 'Rural Youth Empowerment' },
  { value: 'digital_inclusion', label: 'Digital Inclusion' },
  { value: 'artificial_intelligence', label: 'Ethics in AI' },
  { value: 'cybersecurity', label: 'Cybersecurity' },
  { value: 'internet_governance', label: 'Internet Governance' },
  { value: 'cultural_heritage', label: 'Cultural Heritage' },
  { value: 'film', label: 'Film & Documentary' },
  { value: 'music', label: 'Music & Performing Arts' },
  { value: 'visual_arts', label: 'Visual Arts' },
  { value: 'photography', label: 'Photography' },
  { value: 'migration', label: 'Migration & Diaspora' },
  { value: 'child_protection', label: 'Child Protection' },
  { value: 'seniors', label: 'Elderly & Seniors' },
  { value: 'youth_justice', label: 'Youth Justice' },
  { value: 'humanitarian_aid', label: 'Humanitarian Aid' },
  { value: 'animal_welfare', label: 'Animal Welfare' },
  { value: 'fisheries', label: 'Fisheries & Aquaculture' },
  { value: 'green_jobs', label: 'Green Jobs' },
  { value: 'eco_tourism', label: 'Eco-Tourism' },
  { value: 'local_governance', label: 'Local Governance' },
  { value: 'open_government', label: 'Open Government' },
  { value: 'freedom_of_expression', label: 'Freedom of Expression' },
  { value: 'anti_corruption', label: 'Anti-Corruption' },
  { value: 'supply_chains', label: 'Sustainable Supply Chains' },
  { value: 'consumer_rights', label: 'Consumer Rights' },
  { value: 'circular_economy', label: 'Circular Economy' },
  { value: 'zero_waste', label: 'Zero Waste' },
  { value: 'carbon_markets', label: 'Carbon Markets & Finance' },
  { value: 'youth_activism', label: 'Youth Activism' },
  { value: 'independent_media', label: 'Independent Media' },
  { value: 'clean_energy', label: 'Clean Energy' },
  { value: 'green_tech', label: 'Green Technology' },
  { value: 'biodiversity', label: 'Biodiversity' },
  { value: 'soil_conservation', label: 'Soil Conservation' },
  { value: 'sustainable_agriculture', label: 'Sustainable Agriculture' },
  { value: 'organic_farming', label: 'Organic Farming' },
  { value: 'agroforestry', label: 'Agroforestry' },
  { value: 'food_innovation', label: 'Food Innovation' },
  { value: 'nutrition', label: 'Nutrition & Dietetics' },
  { value: 'water_management', label: 'Water Resource Management' },
  { value: 'climate_adaptation', label: 'Climate Adaptation' },
  { value: 'climate_mitigation', label: 'Climate Mitigation' },
  { value: 'disaster_risk_reduction', label: 'Disaster Risk Reduction' },
  { value: 'emergency_preparedness', label: 'Emergency Preparedness' },
  { value: 'housing', label: 'Affordable Housing' },
  { value: 'homelessness', label: 'Homelessness Prevention' },
  { value: 'urban_planning', label: 'Urban Planning' },
  { value: 'smart_cities', label: 'Smart Cities' },
  { value: 'public_transport', label: 'Public Transportation' },
  { value: 'cycling', label: 'Cycling & Pedestrian Infrastructure' },
  { value: 'electric_vehicles', label: 'Electric Vehicles' },
  { value: 'energy_efficiency', label: 'Energy Efficiency' },
  { value: 'solar_energy', label: 'Solar Energy' },
  { value: 'wind_energy', label: 'Wind Energy' },
  { value: 'hydropower', label: 'Hydropower' },
  { value: 'geothermal', label: 'Geothermal Energy' },
  { value: 'bioenergy', label: 'Bioenergy' },
  { value: 'climate_tech', label: 'Climate Technology' },
  { value: 'carbon_capture', label: 'Carbon Capture & Storage' },
  { value: 'climate_finance', label: 'Climate Finance' },
  { value: 'green_bonds', label: 'Green Bonds' },
  { value: 'sustainable_finance', label: 'Sustainable Finance' },
  { value: 'microfinance', label: 'Microfinance' },
  { value: 'impact_investing', label: 'Impact Investing' },
  { value: 'social_entrepreneurship', label: 'Social Entrepreneurship' },
  { value: 'cooperatives', label: 'Cooperatives' },
  { value: 'small_business', label: 'Small Business Development' },
  { value: 'trade', label: 'Trade & Commerce' },
  { value: 'export_promotion', label: 'Export Promotion' },
  { value: 'rural_economy', label: 'Rural Economy' },
  { value: 'tourism', label: 'Sustainable Tourism' },
  { value: 'adventure_tourism', label: 'Adventure Tourism' },
  { value: 'cultural_tourism', label: 'Cultural Tourism' },
  { value: 'community_tourism', label: 'Community-Based Tourism' },
  { value: 'heritage_preservation', label: 'Heritage Preservation' },
  { value: 'archaeology', label: 'Archaeology' },
  { value: 'museums', label: 'Museums & Exhibitions' },
  { value: 'artisan_crafts', label: 'Artisan Crafts' },
  { value: 'traditional_knowledge', label: 'Traditional Knowledge' },
  { value: 'indigenous_rights', label: 'Indigenous Rights' },
  { value: 'land_rights', label: 'Land Rights' },
  { value: 'tenure_reform', label: 'Land Tenure Reform' },
  { value: 'social_inclusion', label: 'Social Inclusion' },
  { value: 'racial_equity', label: 'Racial Equity' },
  { value: 'lgbtq_rights', label: 'LGBTQ+ Rights' },
  { value: 'minority_rights', label: 'Minority Rights' },
  { value: 'diversity_inclusion', label: 'Diversity & Inclusion' },
  { value: 'equity_in_education', label: 'Equity in Education' },
  { value: 'special_education', label: 'Special Education' },
  { value: 'vocational_training', label: 'Vocational Training' },
  { value: 'adult_education', label: 'Adult Education' },
  { value: 'teacher_training', label: 'Teacher Training' },
  { value: 'curriculum_development', label: 'Curriculum Development' },
  { value: 'education_reform', label: 'Education Reform' },
  { value: 'school_infrastructure', label: 'School Infrastructure' },
  { value: 'education_tech', label: 'Education Technology' },
  { value: 'online_learning', label: 'Online Learning Platforms' },
  { value: 'open_education', label: 'Open Education Resources' },
  { value: 'science_education', label: 'Science Education' },
  { value: 'math_education', label: 'Mathematics Education' },
  { value: 'language_education', label: 'Language Education' },
  { value: 'arts_education', label: 'Arts Education' },
  { value: 'music_education', label: 'Music Education' },
  { value: 'physical_education', label: 'Physical Education' },
  { value: 'health_education', label: 'Health Education' },
  { value: 'civic_education', label: 'Civic Education' },
  { value: 'global_education', label: 'Global Education' },
  { value: 'peace_education', label: 'Peace Education' },
  { value: 'human_rights_education', label: 'Human Rights Education' },
  { value: 'environmental_education', label: 'Environmental Education' },
  { value: 'climate_education', label: 'Climate Change Education' },
  { value: 'sustainability_education', label: 'Sustainability Education' },
  { value: 'financial_education', label: 'Financial Education' },
  { value: 'entrepreneurship_education', label: 'Entrepreneurship Education' },
  { value: 'media_literacy', label: 'Media Literacy' },
  { value: 'digital_citizenship', label: 'Digital Citizenship' },
  { value: 'cyber_education', label: 'Cybersecurity Education' },
  { value: 'stem_education', label: 'STEM Education' },
  { value: 'steam_education', label: 'STEAM Education' },
  { value: 'robotics_education', label: 'Robotics Education' },
  { value: 'ai_education', label: 'AI Education' },
  { value: 'coding_education', label: 'Coding Education' },
  { value: 'data_science_education', label: 'Data Science Education' },
  { value: 'healthcare_training', label: 'Healthcare Training' },
  { value: 'nursing', label: 'Nursing & Midwifery' },
  { value: 'medical_research', label: 'Medical Research' },
  { value: 'global_health', label: 'Global Health' },
  { value: 'community_health', label: 'Community Health' },
  { value: 'health_policy', label: 'Health Policy' },
  { value: 'health_equity', label: 'Health Equity' },
  { value: 'mental_health_services', label: 'Mental Health Services' },
  { value: 'substance_abuse', label: 'Substance Abuse Treatment' },
  { value: 'addiction_recovery', label: 'Addiction Recovery' },
  { value: 'chronic_disease', label: 'Chronic Disease Management' },
  { value: 'cancer_research', label: 'Cancer Research' },
  { value: 'diabetes', label: 'Diabetes Management' },
  { value: 'cardiovascular_health', label: 'Cardiovascular Health' },
  { value: 'neurology', label: 'Neurology & Brain Health' },
  { value: 'aging', label: 'Aging & Gerontology' },
  { value: 'palliative_care', label: 'Palliative Care' },
  { value: 'emergency_medicine', label: 'Emergency Medicine' },
  { value: 'trauma_care', label: 'Trauma Care' },
  { value: 'veterinary', label: 'Veterinary Medicine' },
  { value: 'animal_rescue', label: 'Animal Rescue' },
  { value: 'pet_adoption', label: 'Pet Adoption' },
  { value: 'wildlife_rehabilitation', label: 'Wildlife Rehabilitation' },
  { value: 'marine_biology', label: 'Marine Biology' },
  { value: 'ocean_conservation', label: 'Ocean Conservation' },
  { value: 'coral_reefs', label: 'Coral Reef Restoration' },
  { value: 'fisheries_management', label: 'Fisheries Management' },
  { value: 'aquaculture', label: 'Sustainable Aquaculture' },
  { value: 'water_quality', label: 'Water Quality' },
  { value: 'sanitation', label: 'Sanitation Systems' },
  { value: 'wastewater', label: 'Wastewater Treatment' },
  { value: 'recycling', label: 'Recycling Programs' },
  { value: 'plastic_pollution', label: 'Plastic Pollution Reduction' },
  { value: 'air_quality', label: 'Air Quality' },
  { value: 'pollution_control', label: 'Pollution Control' },
  { value: 'renewable_resources', label: 'Renewable Resources' },
  { value: 'natural_resources', label: 'Natural Resource Management' },
  { value: 'forest_management', label: 'Forest Management' },
  { value: 'reforestation', label: 'Reforestation' },
  { value: 'deforestation', label: 'Anti-Deforestation' },
  { value: 'ecosystem_restoration', label: 'Ecosystem Restoration' },
  { value: 'wetlands', label: 'Wetlands Conservation' },
  { value: 'desertification', label: 'Desertification Prevention' },
  { value: 'land_restoration', label: 'Land Restoration' },
  { value: 'soil_health', label: 'Soil Health' },
  { value: 'permaculture', label: 'Permaculture' },
  { value: 'urban_farming', label: 'Urban Farming' },
  { value: 'community_gardens', label: 'Community Gardens' },
  { value: 'food_justice', label: 'Food Justice' },
  { value: 'hunger_relief', label: 'Hunger Relief' },
  { value: 'food_banks', label: 'Food Banks' },
  { value: 'nutrition_programs', label: 'Nutrition Programs' },
  { value: 'child_nutrition', label: 'Child Nutrition' },
  { value: 'school_meals', label: 'School Meals' },
  { value: 'agribusiness', label: 'Agribusiness' },
  { value: 'rural_finance', label: 'Rural Finance' },
  { value: 'cooperative_farming', label: 'Cooperative Farming' },
  { value: 'seed_banks', label: 'Seed Banks' },
  { value: 'crop_diversity', label: 'Crop Diversity' },
  { value: 'climate_smart_agriculture', label: 'Climate-Smart Agriculture' },
  { value: 'water_efficiency', label: 'Water Efficiency' },
  { value: 'irrigation', label: 'Irrigation Systems' },
  { value: 'drought_resilience', label: 'Drought Resilience' },
  { value: 'flood_management', label: 'Flood Management' },
  { value: 'climate_resilience', label: 'Climate Resilience' },
  { value: 'disaster_recovery', label: 'Disaster Recovery' },
  { value: 'humanitarian_response', label: 'Humanitarian Response' },
  { value: 'refugee_support', label: 'Refugee Support' },
  { value: 'asylum_seekers', label: 'Asylum Seekers' },
  { value: 'forced_migration', label: 'Forced Migration' },
  { value: 'integration', label: 'Immigrant Integration' },
  { value: 'multiculturalism', label: 'Multiculturalism' },
  { value: 'intercultural_dialogue', label: 'Intercultural Dialogue' },
  { value: 'community_cohesion', label: 'Community Cohesion' },
  { value: 'social_services', label: 'Social Services' },
  { value: 'public_welfare', label: 'Public Welfare' },
  { value: 'child_welfare', label: 'Child Welfare' },
  { value: 'family_services', label: 'Family Services' },
  { value: 'youth_services', label: 'Youth Services' },
  { value: 'elderly_services', label: 'Elderly Services' },
  { value: 'disability_services', label: 'Disability Services' },
  { value: 'mental_health_support', label: 'Mental Health Support' },
  { value: 'community_centers', label: 'Community Centers' },
  { value: 'public_safety', label: 'Public Safety' },
  { value: 'crime_prevention', label: 'Crime Prevention' },
  { value: 'juvenile_justice', label: 'Juvenile Justice' },
  { value: 'reentry_programs', label: 'Reentry Programs' },
  { value: 'prison_reform', label: 'Prison Reform' },
  { value: 'restorative_justice', label: 'Restorative Justice' },
  { value: 'legal_aid', label: 'Legal Aid' },
  { value: 'access_to_justice', label: 'Access to Justice' },
  { value: 'judicial_reform', label: 'Judicial Reform' },
  { value: 'rule_of_law', label: 'Rule of Law' },
  { value: 'electoral_reform', label: 'Electoral Reform' },
  { value: 'voter_education', label: 'Voter Education' },
  { value: 'civic_participation', label: 'Civic Participation' },
  { value: 'grassroots', label: 'Grassroots Movements' },
  { value: 'community_organizing', label: 'Community Organizing' },
  { value: 'activism', label: 'Activism' },
  { value: 'advocacy', label: 'Advocacy' },
  { value: 'public_policy', label: 'Public Policy' },
  { value: 'governance_reform', label: 'Governance Reform' },
  { value: 'transparency', label: 'Transparency & Accountability' },
  { value: 'whistleblower_protection', label: 'Whistleblower Protection' },
  { value: 'data_privacy', label: 'Data Privacy' },
  { value: 'digital_rights', label: 'Digital Rights' },
  { value: 'internet_access', label: 'Internet Access' },
  { value: 'broadband', label: 'Broadband Expansion' },
  { value: 'tech_access', label: 'Technology Access' },
  { value: 'innovation_hubs', label: 'Innovation Hubs' },
  { value: 'tech_incubators', label: 'Tech Incubators' },
  { value: 'startup_ecosystem', label: 'Startup Ecosystem' },
  { value: 'venture_capital', label: 'Venture Capital' },
  { value: 'angel_investing', label: 'Angel Investing' },
  { value: 'crowdfunding', label: 'Crowdfunding' },
  { value: 'social_impact', label: 'Social Impact' },
  { value: 'corporate_social_responsibility', label: 'Corporate Social Responsibility' },
  { value: 'ethical_business', label: 'Ethical Business Practices' },
  { value: 'fair_trade', label: 'Fair Trade' },
  { value: 'labor_rights', label: 'Labor Rights' },
  { value: 'worker_cooperatives', label: 'Worker Cooperatives' },
  { value: 'unionization', label: 'Unionization' },
  { value: 'workplace_safety', label: 'Workplace Safety' },
  { value: 'job_training', label: 'Job Training' },
  { value: 'employment_services', label: 'Employment Services' },
  { value: 'career_development', label: 'Career Development' },
  { value: 'professional_development', label: 'Professional Development' },
  { value: 'mentorship', label: 'Mentorship Programs' },
  { value: 'leadership_training', label: 'Leadership Training' },
  { value: 'youth_leadership', label: 'Youth Leadership' },
  { value: 'women_leadership', label: 'Women in Leadership' },
  { value: 'minority_leadership', label: 'Minority Leadership' },
  { value: 'indigenous_leadership', label: 'Indigenous Leadership' },
  { value: 'community_leadership', label: 'Community Leadership' },
  { value: 'nonprofit_leadership', label: 'Nonprofit Leadership' },
  { value: 'philanthropic_leadership', label: 'Philanthropic Leadership' },
];