const tagsOptions = [
  { value: 'sustainability', label: 'Sustainability' },
  { value: 'innovation', label: 'Innovation' },
  { value: 'education', label: 'Education' },
  { value: 'technology', label: 'Technology' },
  { value: 'healthcare', label: 'Healthcare' },
  { value: 'youth', label: 'Youth' },
  { value: 'research', label: 'Research' },
  { value: 'scholarships', label: 'Scholarships' },
  { value: 'community', label: 'Community' },
  { value: 'environment', label: 'Environment' },
  { value: 'climate_change', label: 'Climate Change' },
  { value: 'social_justice', label: 'Social Justice' },
  { value: 'arts', label: 'Arts' },
  { value: 'culture', label: 'Culture' },
  { value: 'diversity', label: 'Diversity' },
  { value: 'inclusion', label: 'Inclusion' },
  { value: 'STEM', label: 'STEM' },
  { value: 'agriculture', label: 'Agriculture' },
  { value: 'entrepreneurship', label: 'Entrepreneurship' },
  { value: 'women_empowerment', label: 'Women Empowerment' },
  { value: 'rural_development', label: 'Rural Development' },
  { value: 'urban_development', label: 'Urban Development' },
  { value: 'public_health', label: 'Public Health' },
  { value: 'mental_health', label: 'Mental Health' },
  { value: 'disaster_relief', label: 'Disaster Relief' },
  { value: 'human_rights', label: 'Human Rights' },
  { value: 'poverty_reduction', label: 'Poverty Reduction' },
  { value: 'renewable_energy', label: 'Renewable Energy' },
  { value: 'water_sanitation', label: 'Water & Sanitation' },
  { value: 'food_security', label: 'Food Security' },
  { value: 'literacy', label: 'Literacy' },
  { value: 'vocational_training', label: 'Vocational Training' },
  { value: 'microfinance', label: 'Microfinance' },
  { value: 'global_health', label: 'Global Health' },
  { value: 'indigenous_rights', label: 'Indigenous Rights' },
  { value: 'refugee_support', label: 'Refugee Support' },
  { value: 'gender_equality', label: 'Gender Equality' },
  { value: 'climate_action', label: 'Climate Action' },
  { value: 'wildlife_conservation', label: 'Wildlife Conservation' },
  { value: 'ocean_protection', label: 'Ocean Protection' },
  { value: 'forest_conservation', label: 'Forest Conservation' },
  { value: 'sustainable_agriculture', label: 'Sustainable Agriculture' },
  { value: 'clean_energy', label: 'Clean Energy' },
  { value: 'waste_management', label: 'Waste Management' },
  { value: 'recycling', label: 'Recycling' },
  { value: 'education_reform', label: 'Education Reform' },
  { value: 'digital_literacy', label: 'Digital Literacy' },
  { value: 'AI_research', label: 'AI Research' },
  { value: 'biotechnology', label: 'Biotechnology' },
  { value: 'medical_research', label: 'Medical Research' },
  { value: 'public_policy', label: 'Public Policy' },
  { value: 'economic_development', label: 'Economic Development' },
  { value: 'social_entrepreneurship', label: 'Social Entrepreneurship' },
  { value: 'youth_leadership', label: 'Youth Leadership' },
  { value: 'community_engagement', label: 'Community Engagement' },
  { value: 'cultural_preservation', label: 'Cultural Preservation' },
  { value: 'disability_rights', label: 'Disability Rights' },
  { value: 'LGBTQ_rights', label: 'LGBTQ+ Rights' },
  { value: 'veteran_support', label: 'Veteran Support' },
  { value: 'elderly_care', label: 'Elderly Care' },
  { value: 'child_welfare', label: 'Child Welfare' },
  { value: 'peacebuilding', label: 'Peacebuilding' },
  { value: 'conflict_resolution', label: 'Conflict Resolution' },
  { value: 'humanitarian_aid', label: 'Humanitarian Aid' },
  { value: 'global_partnerships', label: 'Global Partnerships' },
  { value: 'civic_engagement', label: 'Civic Engagement' },
  { value: 'anti_corruption', label: 'Anti-Corruption' },
  { value: 'legal_aid', label: 'Legal Aid' },
  { value: 'public_safety', label: 'Public Safety' },
  { value: 'infrastructure', label: 'Infrastructure' },
  { value: 'transportation', label: 'Transportation' },
  { value: 'urban_planning', label: 'Urban Planning' },
  { value: 'rural_health', label: 'Rural Health' },
  { value: 'tech_innovation', label: 'Tech Innovation' },
  { value: 'data_science', label: 'Data Science' },
  { value: 'machine_learning', label: 'Machine Learning' },
  { value: 'cybersecurity', label: 'Cybersecurity' },
  { value: 'blockchain', label: 'Blockchain' },
  { value: 'fintech', label: 'Fintech' },
  { value: 'edtech', label: 'EdTech' },
  { value: 'healthtech', label: 'HealthTech' },
  { value: 'agritech', label: 'AgriTech' },
  { value: 'space_research', label: 'Space Research' },
  { value: 'renewable_resources', label: 'Renewable Resources' },
  { value: 'energy_efficiency', label: 'Energy Efficiency' },
  { value: 'sustainable_design', label: 'Sustainable Design' },
  { value: 'green_technology', label: 'Green Technology' },
  { value: 'social_impact', label: 'Social Impact' },
  { value: 'philanthropy', label: 'Philanthropy' },
  { value: 'nonprofit', label: 'Nonprofit' },
  { value: 'volunteerism', label: 'Volunteerism' },
  { value: 'grassroots', label: 'Grassroots' },
  { value: 'capacity_building', label: 'Capacity Building' },
  { value: 'advocacy', label: 'Advocacy' },
  { value: 'policy_reform', label: 'Policy Reform' },
  { value: 'community_health', label: 'Community Health' },
  { value: 'youth_mentorship', label: 'Youth Mentorship' },
  { value: 'cultural_exchange', label: 'Cultural Exchange' },
  { value: 'global_education', label: 'Global Education' },
];