export const tagsOptions = [
  { value: 'sustainability', label: 'Sustainability' },
  { value: 'innovation', label: 'Innovation' },
  { value: 'education', label: 'Education' },
  { value: 'technology', label: 'Technology' },
  { value: 'healthcare', label: 'Healthcare' },
  { value: 'youth', label: 'Youth' },
  { value: 'research', label: 'Research' },
  { value: 'scholarships', label: 'Scholarships' },
  { value: 'community', label: 'Community' },
  { value: 'environment', label: 'Environment' },
  { value: 'climate_change', label: 'Climate Change' },
  { value: 'social_justice', label: 'Social Justice' },
  { value: 'arts', label: 'Arts' },
  { value: 'culture', label: 'Culture' },
  { value: 'diversity', label: 'Diversity' },
  { value: 'inclusion', label: 'Inclusion' },
  { value: 'STEM', label: 'STEM' },
  { value: 'agriculture', label: 'Agriculture' },
  { value: 'entrepreneurship', label: 'Entrepreneurship' },
  { value: 'women_empowerment', label: 'Women Empowerment' },
  { value: 'rural_development', label: 'Rural Development' },
  { value: 'urban_development', label: 'Urban Development' },
  { value: 'public_health', label: 'Public Health' },
  { value: 'mental_health', label: 'Mental Health' },
  { value: 'disaster_relief', label: 'Disaster Relief' },
  { value: 'human_rights', label: 'Human Rights' },
  { value: 'poverty_reduction', label: 'Poverty Reduction' },
  { value: 'renewable_energy', label: 'Renewable Energy' },
  { value: 'water_sanitation', label: 'Water & Sanitation' },
  { value: 'food_security', label: 'Food Security' },
  { value: 'literacy', label: 'Literacy' },
  { value: 'vocational_training', label: 'Vocational Training' },
  { value: 'microfinance', label: 'Microfinance' },
  { value: 'global_health', label: 'Global Health' },
  { value: 'indigenous_rights', label: 'Indigenous Rights' },
  { value: 'refugee_support', label: 'Refugee Support' },
  { value: 'gender_equality', label: 'Gender Equality' },
  { value: 'climate_action', label: 'Climate Action' },
  { value: 'wildlife_conservation', label: 'Wildlife Conservation' },
  { value: 'ocean_protection', label: 'Ocean Protection' },
  { value: 'forest_conservation', label: 'Forest Conservation' },
  { value: 'sustainable_agriculture', label: 'Sustainable Agriculture' },
  { value: 'clean_energy', label: 'Clean Energy' },
  { value: 'waste_management', label: 'Waste Management' },
  { value: 'recycling', label: 'Recycling' },
  { value: 'education_reform', label: 'Education Reform' },
  { value: 'digital_literacy', label: 'Digital Literacy' },
  { value: 'AI_research', label: 'AI Research' },
  { value: 'biotechnology', label: 'Biotechnology' },
  { value: 'medical_research', label: 'Medical Research' },
  { value: 'public_policy', label: 'Public Policy' },
  { value: 'economic_development', label: 'Economic Development' },
  { value: 'social_entrepreneurship', label: 'Social Entrepreneurship' },
  { value: 'youth_leadership', label: 'Youth Leadership' },
  { value: 'community_engagement', label: 'Community Engagement' },
  { value: 'cultural_preservation', label: 'Cultural Preservation' },
  { value: 'disability_rights', label: 'Disability Rights' },
  { value: 'LGBTQ_rights', label: 'LGBTQ+ Rights' },
  { value: 'veteran_support', label: 'Veteran Support' },
  { value: 'elderly_care', label: 'Elderly Care' },
  { value: 'child_welfare', label: 'Child Welfare' },
  { value: 'peacebuilding', label: 'Peacebuilding' },
  { value: 'conflict_resolution', label: 'Conflict Resolution' },
  { value: 'humanitarian_aid', label: 'Humanitarian Aid' },
  { value: 'global_partnerships', label: 'Global Partnerships' },
  { value: 'civic_engagement', label: 'Civic Engagement' },
  { value: 'anti_corruption', label: 'Anti-Corruption' },
  { value: 'legal_aid', label: 'Legal Aid' },
  { value: 'public_safety', label: 'Public Safety' },
  { value: 'infrastructure', label: 'Infrastructure' },
  { value: 'transportation', label: 'Transportation' },
  { value: 'urban_planning', label: 'Urban Planning' },
  { value: 'rural_health', label: 'Rural Health' },
  { value: 'tech_innovation', label: 'Tech Innovation' },
  { value: 'data_science', label: 'Data Science' },
  { value: 'machine_learning', label: 'Machine Learning' },
  { value: 'cybersecurity', label: 'Cybersecurity' },
  { value: 'blockchain', label: 'Blockchain' },
  { value: 'fintech', label: 'Fintech' },
  { value: 'edtech', label: 'EdTech' },
  { value: 'healthtech', label: 'HealthTech' },
  { value: 'agritech', label: 'AgriTech' },
  { value: 'space_research', label: 'Space Research' },
  { value: 'renewable_resources', label: 'Renewable Resources' },
  { value: 'energy_efficiency', label: 'Energy Efficiency' },
  { value: 'sustainable_design', label: 'Sustainable Design' },
  { value: 'green_technology', label: 'Green Technology' },
  { value: 'social_impact', label: 'Social Impact' },
  { value: 'philanthropy', label: 'Philanthropy' },
  { value: 'nonprofit', label: 'Nonprofit' },
  { value: 'volunteerism', label: 'Volunteerism' },
  { value: 'grassroots', label: 'Grassroots' },
  { value: 'capacity_building', label: 'Capacity Building' },
  { value: 'advocacy', label: 'Advocacy' },
  { value: 'policy_reform', label: 'Policy Reform' },
  { value: 'community_health', label: 'Community Health' },
  { value: 'youth_mentorship', label: 'Youth Mentorship' },
  { value: 'cultural_exchange', label: 'Cultural Exchange' },
  { value: 'global_education', label: 'Global Education' },
  { value: 'fellowships', label: 'Fellowships' },
  { value: 'conferences', label: 'Conferences' },
  { value: 'workshops', label: 'Workshops' },
  { value: 'seminars', label: 'Seminars' },
  { value: 'training_programs', label: 'Training Programs' },
  { value: 'grants', label: 'Grants' },
  { value: 'funding_opportunities', label: 'Funding Opportunities' },
  { value: 'seed_funding', label: 'Seed Funding' },
  { value: 'project_funding', label: 'Project Funding' },
  { value: 'research_grants', label: 'Research Grants' },
  { value: 'travel_grants', label: 'Travel Grants' },
  { value: 'study_abroad', label: 'Study Abroad' },
  { value: 'internships', label: 'Internships' },
  { value: 'residencies', label: 'Residencies' },
  { value: 'artist_grants', label: 'Artist Grants' },
  { value: 'science_research', label: 'Science Research' },
  { value: 'social_sciences', label: 'Social Sciences' },
  { value: 'humanities', label: 'Humanities' },
  { value: 'postdoctoral_fellowships', label: 'Postdoctoral Fellowships' },
  { value: 'doctoral_fellowships', label: 'Doctoral Fellowships' },
  { value: 'undergraduate_scholarships', label: 'Undergraduate Scholarships' },
  { value: 'graduate_scholarships', label: 'Graduate Scholarships' },
  { value: 'professional_development', label: 'Professional Development' },
  { value: 'leadership_training', label: 'Leadership Training' },
  { value: 'mentorship_programs', label: 'Mentorship Programs' },
  { value: 'networking_events', label: 'Networking Events' },
  { value: 'hackathons', label: 'Hackathons' },
  { value: 'innovation_challenges', label: 'Innovation Challenges' },
  { value: 'startup_incubators', label: 'Startup Incubators' },
  { value: 'accelerators', label: 'Accelerators' },
  { value: 'crowdfunding', label: 'Crowdfunding' },
  { value: 'impact_investing', label: 'Impact Investing' },
  { value: 'venture_philanthropy', label: 'Venture Philanthropy' },
  { value: 'open_access', label: 'Open Access' },
  { value: 'knowledge_sharing', label: 'Knowledge Sharing' },
  { value: 'collaborative_research', label: 'Collaborative Research' },
  { value: 'interdisciplinary_research', label: 'Interdisciplinary Research' },
  { value: 'community_based_research', label: 'Community-Based Research' },
  { value: 'action_research', label: 'Action Research' },
  { value: 'policy_analysis', label: 'Policy Analysis' },
  { value: 'evaluation_studies', label: 'Evaluation Studies' },
  { value: 'impact_assessment', label: 'Impact Assessment' },
  { value: 'sustainable_funding', label: 'Sustainable Funding' },
  { value: 'partnership_development', label: 'Partnership Development' },
  { value: 'cross_sector_collaboration', label: 'Cross-Sector Collaboration' },
  { value: 'private_sector_engagement', label: 'Private Sector Engagement' },
  { value: 'government_funding', label: 'Government Funding' },
  { value: 'foundation_grants', label: 'Foundation Grants' },
  { value: 'corporate_social_responsibility', label: 'Corporate Social Responsibility' },
  { value: 'employee_engagement', label: 'Employee Engagement' },
  { value: 'social_innovation', label: 'Social Innovation' },
  { value: 'design_thinking', label: 'Design Thinking' },
  { value: 'systems_change', label: 'Systems Change' },
  { value: 'scaling_impact', label: 'Scaling Impact' },
  { value: 'replication_models', label: 'Replication Models' },
  { value: 'franchise_models', label: 'Franchise Models' },
  { value: 'open_source', label: 'Open Source' },
  { value: 'tech_for_good', label: 'Tech for Good' },
  { value: 'digital_transformation', label: 'Digital Transformation' },
  { value: 'smart_cities', label: 'Smart Cities' },
  { value: 'resilient_communities', label: 'Resilient Communities' },
  { value: 'sdg1_no_poverty', label: 'SDG 1: No Poverty' },
  { value: 'sdg2_zero_hunger', label: 'SDG 2: Zero Hunger' },
  { value: 'sdg3_good_health_wellbeing', label: 'SDG 3: Good Health and Well-being' },
  { value: 'sdg4_quality_education', label: 'SDG 4: Quality Education' },
  { value: 'sdg5_gender_equality', label: 'SDG 5: Gender Equality' },
  { value: 'sdg6_clean_water_sanitation', label: 'SDG 6: Clean Water and Sanitation' },
  { value: 'sdg7_affordable_clean_energy', label: 'SDG 7: Affordable and Clean Energy' },
  { value: 'sdg8_decent_work_economic_growth', label: 'SDG 8: Decent Work and Economic Growth' },
  { value: 'sdg9_industry_innovation_infrastructure', label: 'SDG 9: Industry, Innovation and Infrastructure' },
  { value: 'sdg10_reduced_inequalities', label: 'SDG 10: Reduced Inequalities' },
  { value: 'sdg11_sustainable_cities_communities', label: 'SDG 11: Sustainable Cities and Communities' },
  { value: 'sdg12_responsible_consumption_production', label: 'SDG 12: Responsible Consumption and Production' },
  { value: 'sdg13_climate_action', label: 'SDG 13: Climate Action' },
  { value: 'sdg14_life_below_water', label: 'SDG 14: Life Below Water' },
  { value: 'sdg15_life_on_land', label: 'SDG 15: Life on Land' },
  { value: 'sdg16_peace_justice_strong_institutions', label: 'SDG 16: Peace, Justice and Strong Institutions' },
  { value: 'sdg17_partnerships_for_goals', label: 'SDG 17: Partnerships for the Goals' },
  { value: 'primary_healthcare', label: 'Primary Healthcare' },
  { value: 'maternal_health', label: 'Maternal Health' },
  { value: 'child_health', label: 'Child Health' },
  { value: 'infectious_diseases', label: 'Infectious Diseases' },
  { value: 'non_communicable_diseases', label: 'Non-Communicable Diseases' },
  { value: 'cancer_research', label: 'Cancer Research' },
  { value: 'cardiovascular_health', label: 'Cardiovascular Health' },
  { value: 'diabetes_management', label: 'Diabetes Management' },
  { value: 'vaccination_programs', label: 'Vaccination Programs' },
  { value: 'health_education', label: 'Health Education' },
  { value: 'nutrition_programs', label: 'Nutrition Programs' },
  { value: 'telemedicine', label: 'Telemedicine' },
  { value: 'health_systems_strengthening', label: 'Health Systems Strengthening' },
  { value: 'emergency_medical_services', label: 'Emergency Medical Services' },
  { value: 'reproductive_health', label: 'Reproductive Health' },
  { value: 'sexual_health', label: 'Sexual Health' },
  { value: 'substance_abuse_prevention', label: 'Substance Abuse Prevention' },
  { value: 'smoking_cessation', label: 'Smoking Cessation' },
  { value: 'health_policy', label: 'Health Policy' },
  { value: 'health_economics', label: 'Health Economics' },
  { value: 'healthcare_access', label: 'Healthcare Access' },
  { value: 'healthcare_equity', label: 'Healthcare Equity' },
  { value: 'genetic_research', label: 'Genetic Research' },
  { value: 'precision_medicine', label: 'Precision Medicine' },
  { value: 'clinical_trials', label: 'Clinical Trials' },
  { value: 'epidemiology', label: 'Epidemiology' },
  { value: 'health_data_analytics', label: 'Health Data Analytics' },
  { value: 'wearable_health_tech', label: 'Wearable Health Tech' },
  { value: 'healthcare_innovation', label: 'Healthcare Innovation' },
  { value: 'geriatric_care', label: 'Geriatric Care' },
  { value: 'palliative_care', label: 'Palliative Care' },
  { value: 'hospice_care', label: 'Hospice Care' },
  { value: 'healthcare_workforce_training', label: 'Healthcare Workforce Training' },
  { value: 'nursing_education', label: 'Nursing Education' },
  { value: 'medical_education', label: 'Medical Education' },
  { value: 'community_health_workers', label: 'Community Health Workers' },
  { value: 'health_promotion', label: 'Health Promotion' },
  { value: 'disease_prevention', label: 'Disease Prevention' },
  { value: 'immunization_research', label: 'Immunization Research' },
  { value: 'antimicrobial_resistance', label: 'Antimicrobial Resistance' },
  { value: 'tropical_diseases', label: 'Tropical Diseases' },
  { value: 'neglected_diseases', label: 'Neglected Diseases' },
  { value: 'health_emergencies', label: 'Health Emergencies' },
  { value: 'pandemic_preparedness', label: 'Pandemic Preparedness' },
  { value: 'climate_resilience', label: 'Climate Resilience' },
  { value: 'carbon_reduction', label: 'Carbon Reduction' },
  { value: 'greenhouse_gas_emissions', label: 'Greenhouse Gas Emissions' },
  { value: 'deforestation_prevention', label: 'Deforestation Prevention' },
  { value: 'reforestation', label: 'Reforestation' },
  { value: 'soil_conservation', label: 'Soil Conservation' },
  { value: 'biodiversity_protection', label: 'Biodiversity Protection' },
  { value: 'ecosystem_restoration', label: 'Ecosystem Restoration' },
  { value: 'marine_conservation', label: 'Marine Conservation' },
  { value: 'coral_reef_protection', label: 'Coral Reef Protection' },
  { value: 'sustainable_fisheries', label: 'Sustainable Fisheries' },
  { value: 'pollution_control', label: 'Pollution Control' },
  { value: 'air_quality', label: 'Air Quality' },
  { value: 'water_quality', label: 'Water Quality' },
  { value: 'environmental_justice', label: 'Environmental Justice' },
  { value: 'climate_adaptation', label: 'Climate Adaptation' },
  { value: 'climate_mitigation', label: 'Climate Mitigation' },
  { value: 'circular_economy', label: 'Circular Economy' },
  { value: 'sustainable_supply_chains', label: 'Sustainable Supply Chains' },
  { value: 'green_manufacturing', label: 'Green Manufacturing' },
  { value: 'sustainable_packaging', label: 'Sustainable Packaging' },
  { value: 'energy_transition', label: 'Energy Transition' },
  { value: 'solar_energy', label: 'Solar Energy' },
  { value: 'wind_energy', label: 'Wind Energy' },
  { value: 'hydropower', label: 'Hydropower' },
  { value: 'geothermal_energy', label: 'Geothermal Energy' },
  { value: 'bioenergy', label: 'Bioenergy' },
  { value: 'energy_storage', label: 'Energy Storage' },
  { value: 'smart_grids', label: 'Smart Grids' },
  { value: 'green_buildings', label: 'Green Buildings' },
  { value: 'sustainable_architecture', label: 'Sustainable Architecture' },
  { value: 'climate_tech', label: 'Climate Tech' },
  { value: 'carbon_capture', label: 'Carbon Capture' },
  { value: 'climate_policy', label: 'Climate Policy' },
  { value: 'environmental_governance', label: 'Environmental Governance' },
  { value: 'climate_finance', label: 'Climate Finance' },
  { value: 'green_bonds', label: 'Green Bonds' },
  { value: 'sustainable_investments', label: 'Sustainable Investments' },
  { value: 'esg_investing', label: 'ESG Investing' },
  { value: 'environmental_education', label: 'Environmental Education' },
  { value: 'climate_literacy', label: 'Climate Literacy' },
  { value: 'sustainable_tourism', label: 'Sustainable Tourism' },
  { value: 'ecotourism', label: 'Ecotourism' },
  { value: 'organic_farming', label: 'Organic Farming' },
  { value: 'permaculture', label: 'Permaculture' },
  { value: 'agroforestry', label: 'Agroforestry' },
  { value: 'precision_agriculture', label: 'Precision Agriculture' },
  { value: 'food_systems', label: 'Food Systems' },
  { value: 'sustainable_food', label: 'Sustainable Food' },
  { value: 'plant_based_diets', label: 'Plant-Based Diets' },
  { value: 'food_waste_reduction', label: 'Food Waste Reduction' },
  { value: 'urban_farming', label: 'Urban Farming' },
  { value: 'vertical_farming', label: 'Vertical Farming' },
  { value: 'water_management', label: 'Water Management' },
  { value: 'water_conservation', label: 'Water Conservation' },
  { value: 'watershed_management', label: 'Watershed Management' },
  { value: 'desalination', label: 'Desalination' },
  { value: 'water_purification', label: 'Water Purification' },
  { value: 'sanitation_infrastructure', label: 'Sanitation Infrastructure' },
  { value: 'hygiene_promotion', label: 'Hygiene Promotion' },
  { value: 'early_childhood_education', label: 'Early Childhood Education' },
  { value: 'primary_education', label: 'Primary Education' },
  { value: 'secondary_education', label: 'Secondary Education' },
  { value: 'higher_education', label: 'Higher Education' },
  { value: 'adult_education', label: 'Adult Education' },
  { value: 'special_education', label: 'Special Education' },
  { value: 'inclusive_education', label: 'Inclusive Education' },
  { value: 'stem_education', label: 'STEM Education' },
  { value: 'arts_education', label: 'Arts Education' },
  { value: 'civic_education', label: 'Civic Education' },
  { value: 'teacher_training', label: 'Teacher Training' },
  { value: 'curriculum_development', label: 'Curriculum Development' },
  { value: 'education_technology', label: 'Education Technology' },
  { value: 'online_learning', label: 'Online Learning' },
  { value: 'blended_learning', label: 'Blended Learning' },
  { value: 'open_educational_resources', label: 'Open Educational Resources' },
  { value: 'education_equity', label: 'Education Equity' },
  { value: 'girls_education', label: 'Girls’ Education' },
  { value: 'rural_education', label: 'Rural Education' },
  { value: 'education_in_emergencies', label: 'Education in Emergencies' },
  { value: 'school_infrastructure', label: 'School Infrastructure' },
  { value: 'school_meals', label: 'School Meals' },
  { value: 'student_mentorship', label: 'Student Mentorship' },
  { value: 'career_counseling', label: 'Career Counseling' },
  { value: 'financial_literacy', label: 'Financial Literacy' },
  { value: 'entrepreneurship_education', label: 'Entrepreneurship Education' },
  { value: 'life_skills', label: 'Life Skills' },
  { value: 'youth_employment', label: 'Youth Employment' },
  { value: 'job_creation', label: 'Job Creation' },
  { value: 'workforce_development', label: 'Workforce Development' },
  { value: 'skills_training', label: 'Skills Training' },
  { value: 'apprenticeships', label: 'Apprenticeships' },
  { value: 'green_jobs', label: 'Green Jobs' },
  { value: 'digital_skills', label: 'Digital Skills' },
  { value: 'coding_bootcamps', label: 'Coding Bootcamps' },
  { value: 'tech_training', label: 'Tech Training' },
  { value: 'economic_empowerment', label: 'Economic Empowerment' },
  { value: 'small_business_support', label: 'Small Business Support' },
  { value: 'cooperative_development', label: 'Cooperative Development' },
  { value: 'trade_promotion', label: 'Trade Promotion' },
  { value: 'export_development', label: 'Export Development' },
  { value: 'industrial_development', label: 'Industrial Development' },
  { value: 'innovation_hubs', label: 'Innovation Hubs' },
  { value: 'tech_transfer', label: 'Tech Transfer' },
  { value: 'intellectual_property', label: 'Intellectual Property' },
  { value: 'research_commercialization', label: 'Research Commercialization' },
  { value: 'startup_ecosystems', label: 'Startup Ecosystems' },
  { value: 'business_incubation', label: 'Business Incubation' },
  { value: 'angel_investing', label: 'Angel Investing' },
  { value: 'venture_capital', label: 'Venture Capital' },
  { value: 'social_enterprise', label: 'Social Enterprise' },
  { value: 'impact_evaluation', label: 'Impact Evaluation' },
  { value: 'monitoring_evaluation', label: 'Monitoring and Evaluation' },
  { value: 'data_collection', label: 'Data Collection' },
  { value: 'data_analysis', label: 'Data Analysis' },
  { value: 'big_data', label: 'Big Data' },
  { value: 'artificial_intelligence', label: 'Artificial Intelligence' },
  { value: 'quantum_computing', label: 'Quantum Computing' },
  { value: 'robotics', label: 'Robotics' },
  { value: 'internet_of_things', label: 'Internet of Things' },
  { value: '5g_technology', label: '5G Technology' },
  { value: 'digital_infrastructure', label: 'Digital Infrastructure' },
  { value: 'broadband_access', label: 'Broadband Access' },
  { value: 'digital_inclusion', label: 'Digital Inclusion' },
  { value: 'e_governance', label: 'E-Governance' },
  { value: 'open_data', label: 'Open Data' },
  { value: 'smart_government', label: 'Smart Government' },
  { value: 'public_service_delivery', label: 'Public Service Delivery' },
  { value: 'transparency_accountability', label: 'Transparency and Accountability' },
  { value: 'citizen_participation', label: 'Citizen Participation' },
  { value: 'community_organizing', label: 'Community Organizing' },
  { value: 'grassroots_advocacy', label: 'Grassroots Advocacy' },
  { value: 'human_rights_defenders', label: 'Human Rights Defenders' },
  { value: 'freedom_of_expression', label: 'Freedom of Expression' },
  { value: 'press_freedom', label: 'Press Freedom' },
  { value: 'access_to_justice', label: 'Access to Justice' },
  { value: 'rule_of_law', label: 'Rule of Law' },
  { value: 'anti_discrimination', label: 'Anti-Discrimination' },
  { value: 'social_cohesion', label: 'Social Cohesion' },
  { value: 'intercultural_dialogue', label: 'Intercultural Dialogue' },
  { value: 'migration_support', label: 'Migration Support' },
  { value: 'forced_displacement', label: 'Forced Displacement' },
  { value: 'human_trafficking_prevention', label: 'Human Trafficking Prevention' },
  { value: 'child_protection', label: 'Child Protection' },
  { value: 'family_support', label: 'Family Support' },
  { value: 'domestic_violence_prevention', label: 'Domestic Violence Prevention' },
  { value: 'gender_based_violence', label: 'Gender-Based Violence' },
  { value: 'women_leadership', label: 'Women Leadership' },
  { value: 'youth_empowerment', label: 'Youth Empowerment' },
  { value: 'disability_inclusion', label: 'Disability Inclusion' },
  { value: 'accessible_technology', label: 'Accessible Technology' },
  { value: 'universal_design', label: 'Universal Design' },
  { value: 'veteran_services', label: 'Veteran Services' },
  { value: 'homelessness_prevention', label: 'Homelessness Prevention' },
  { value: 'affordable_housing', label: 'Affordable Housing' },
  { value: 'community_development', label: 'Community Development' },
  { value: 'neighborhood_revitalization', label: 'Neighborhood Revitalization' },
  { value: 'public_spaces', label: 'Public Spaces' },
  { value: 'cultural_heritage', label: 'Cultural Heritage' },
  { value: 'traditional_knowledge', label: 'Traditional Knowledge' },
  { value: 'indigenous_languages', label: 'Indigenous Languages' },
  { value: 'oral_history', label: 'Oral History' },
  { value: 'museum_programs', label: 'Museum Programs' },
  { value: 'public_art', label: 'Public Art' },
  { value: 'community_arts', label: 'Community Arts' },
  { value: 'performing_arts', label: 'Performing Arts' },
  { value: 'visual_arts', label: 'Visual Arts' },
  { value: 'literature', label: 'Literature' },
  { value: 'creative_writing', label: 'Creative Writing' },
  { value: 'film_production', label: 'Film Production' },
  { value: 'digital_arts', label: 'Digital Arts' },
  { value: 'music_education', label: 'Music Education' },
  { value: 'cultural_festivals', label: 'Cultural Festivals' },
  { value: 'heritage_tourism', label: 'Heritage Tourism' },
  { value: 'peace_education', label: 'Peace Education' },
  { value: 'mediation_training', label: 'Mediation Training' },
  { value: 'restorative_justice', label: 'Restorative Justice' },
  { value: 'conflict_transformation', label: 'Conflict Transformation' },
  { value: 'interfaith_dialogue', label: 'Interfaith Dialogue' },
  { value: 'disarmament', label: 'Disarmament' },
  { value: 'non_violence', label: 'Non-Violence' },
  { value: 'humanitarian_response', label: 'Humanitarian Response' },
  { value: 'disaster_preparedness', label: 'Disaster Preparedness' },
  { value: 'emergency_relief', label: 'Emergency Relief' },
  { value: 'post_disaster_recovery', label: 'Post-Disaster Recovery' },
  { value: 'resilience_building', label: 'Resilience Building' },
  { value: 'crisis_management', label: 'Crisis Management' },
  { value: 'supply_chain_management', label: 'Supply Chain Management' },
  { value: 'logistics', label: 'Logistics' },
  { value: 'public_private_partnerships', label: 'Public-Private Partnerships' },
  { value: 'multi_stakeholder_collaboration', label: 'Multi-Stakeholder Collaboration' },
  { value: 'global_cooperation', label: 'Global Cooperation' },
  { value: 'south_south_cooperation', label: 'South-South Cooperation' },
  { value: 'triangular_cooperation', label: 'Triangular Cooperation' },
  { value: 'development_aid', label: 'Development Aid' },
  { value: 'foreign_aid', label: 'Foreign Aid' },
  { value: 'bilateral_cooperation', label: 'Bilateral Cooperation' },
  { value: 'multilateral_cooperation', label: 'Multilateral Cooperation' },
  { value: 'ngo_partnerships', label: 'NGO Partnerships' },
  { value: 'community_led_development', label: 'Community-Led Development' },
  { value: 'participatory_development', label: 'Participatory Development' },
  { value: 'bottom_up_approach', label: 'Bottom-Up Approach' },
  { value: 'local_governance', label: 'Local Governance' },
  { value: 'decentralization', label: 'Decentralization' },
  { value: 'municipal_services', label: 'Municipal Services' },
  { value: 'public_administration', label: 'Public Administration' },
  { value: 'institutional_strengthening', label: 'Institutional Strengthening' },
  { value: 'anti_money_laundering', label: 'Anti-Money Laundering' },
  { value: 'financial_transparency', label: 'Financial Transparency' },
  { value: 'tax_justice', label: 'Tax Justice' },
  { value: 'economic_governance', label: 'Economic Governance' },
  { value: 'trade_policy', label: 'Trade Policy' },
  { value: 'regional_integration', label: 'Regional Integration' },
  { value: 'global_trade', label: 'Global Trade' },
  { value: 'supply_chain_resilience', label: 'Supply Chain Resilience' },
  { value: 'disaster_risk_reduction', label: 'Disaster Risk Reduction' },
  { value: 'early_warning_systems', label: 'Early Warning Systems' },
  { value: 'climate_monitoring', label: 'Climate Monitoring' },
  { value: 'environmental_monitoring', label: 'Environmental Monitoring' },
  { value: 'remote_sensing', label: 'Remote Sensing' },
  { value: 'gis_mapping', label: 'GIS Mapping' },
  { value: 'spatial_analysis', label: 'Spatial Analysis' },
  { value: 'urban_resilience', label: 'Urban Resilience' },
  { value: 'rural_resilience', label: 'Rural Resilience' },
  { value: 'community_resilience', label: 'Community Resilience' },
  { value: 'infrastructure_resilience', label: 'Infrastructure Resilience' },
  { value: 'transportation_infrastructure', label: 'Transportation Infrastructure' },
  { value: 'public_transport', label: 'Public Transport' },
  { value: 'sustainable_mobility', label: 'Sustainable Mobility' },
  { value: 'electric_vehicles', label: 'Electric Vehicles' },
  { value: 'cycling_infrastructure', label: 'Cycling Infrastructure' },
  { value: 'walkable_cities', label: 'Walkable Cities' },
  { value: 'urban_green_spaces', label: 'Urban Green Spaces' },
  { value: 'green_infrastructure', label: 'Green Infrastructure' },
  { value: 'low_carbon_cities', label: 'Low-Carbon Cities' },
  { value: 'energy_efficient_cities', label: 'Energy-Efficient Cities' },
  { value: 'smart_urbanism', label: 'Smart Urbanism' },
  { value: 'urban_analytics', label: 'Urban Analytics' },
  { value: 'city_planning', label: 'City Planning' },
  { value: 'housing_policy', label: 'Housing Policy' },
  { value: 'land_use_planning', label: 'Land Use Planning' },
  { value: 'zoning_regulations', label: 'Zoning Regulations' },
  { value: 'real_estate_development', label: 'Real Estate Development' },
  { value: 'sustainable_real_estate', label: 'Sustainable Real Estate' },
  { value: 'affordable_rental_housing', label: 'Affordable Rental Housing' },
  { value: 'homeownership_programs', label: 'Homeownership Programs' },
  { value: 'housing_finance', label: 'Housing Finance' },
  { value: 'micro_mortgages', label: 'Micro-Mortgages' },
  { value: 'financial_inclusion', label: 'Financial Inclusion' },
  { value: 'digital_banking', label: 'Digital Banking' },
  { value: 'mobile_banking', label: 'Mobile Banking' },
  { value: 'micro_savings', label: 'Micro-Savings' },
  { value: 'micro_insurance', label: 'Micro-Insurance' },
  { value: 'financial_education', label: 'Financial Education' },
  { value: 'consumer_protection', label: 'Consumer Protection' },
  { value: 'economic_policy', label: 'Economic Policy' },
  { value: 'fiscal_policy', label: 'Fiscal Policy' },
  { value: 'monetary_policy', label: 'Monetary Policy' },
  { value: 'labor_policy', label: 'Labor Policy' },
  { value: 'social_protection', label: 'Social Protection' },
  { value: 'universal_basic_income', label: 'Universal Basic Income' },
  { value: 'social_safety_nets', label: 'Social Safety Nets' },
  { value: 'pension_reform', label: 'Pension Reform' },
  { value: 'unemployment_support', label: 'Unemployment Support' },
  { value: 'disability_benefits', label: 'Disability Benefits' },
  { value: 'child_benefits', label: 'Child Benefits' },
  { value: 'family_benefits', label: 'Family Benefits' },
  { value: 'welfare_reform', label: 'Welfare Reform' },
  { value: 'social_services', label: 'Social Services' },
  { value: 'community_services', label: 'Community Services' },
  { value: 'youth_services', label: 'Youth Services' },
  { value: 'elderly_services', label: 'Elderly Services' },
  { value: 'mental_health_services', label: 'Mental Health Services' },
  { value: 'addiction_services', label: 'Addiction Services' },
  { value: 'rehabilitation_services', label: 'Rehabilitation Services' },
  { value: 'vocational_rehabilitation', label: 'Vocational Rehabilitation' },
  { value: 'disability_services', label: 'Disability Services' },
  { value: 'inclusive_services', label: 'Inclusive Services' },
  { value: 'public_health_services', label: 'Public Health Services' },
  { value: 'preventive_healthcare', label: 'Preventive Healthcare' },
  { value: 'health_screening', label: 'Health Screening' },
  { value: 'community_clinics', label: 'Community Clinics' },
  { value: 'mobile_health_units', label: 'Mobile Health Units' },
  { value: 'rural_healthcare', label: 'Rural Healthcare' },
  { value: 'urban_healthcare', label: 'Urban Healthcare' },
  { value: 'healthcare_infrastructure', label: 'Healthcare Infrastructure' },
  { value: 'hospital_development', label: 'Hospital Development' },
  { value: 'primary_care_centers', label: 'Primary Care Centers' },
  { value: 'healthcare_financing', label: 'Healthcare Financing' },
  { value: 'health_insurance', label: 'Health Insurance' },
  { value: 'universal_health_coverage', label: 'Universal Health Coverage' },
  { value: 'healthcare_reform', label: 'Healthcare Reform' },
  { value: 'patient_centered_care', label: 'Patient-Centered Care' },
  { value: 'healthcare_quality', label: 'Healthcare Quality' },
  { value: 'healthcare_safety', label: 'Healthcare Safety' },
  { value: 'healthcare_ethics', label: 'Healthcare Ethics' },
  { value: 'bioethics', label: 'Bioethics' },
  { value: 'medical_ethics', label: 'Medical Ethics' },
  { value: 'research_ethics', label: 'Research Ethics' },
  { value: 'clinical_ethics', label: 'Clinical Ethics' },
  { value: 'public_health_ethics', label: 'Public Health Ethics' },
  { value: 'global_health_ethics', label: 'Global Health Ethics' },
  { value: 'health_equity_research', label: 'Health Equity Research' },
  { value: 'social_determinants_of_health', label: 'Social Determinants of Health' },
  { value: 'health_disparities', label: 'Health Disparities' },
  { value: 'minority_health', label: 'Minority Health' },
  { value: 'indigenous_health', label: 'Indigenous Health' },
  { value: 'refugee_health', label: 'Refugee Health' },
  { value: 'migrant_health', label: 'Migrant Health' },
  { value: 'global_health_research', label: 'Global Health Research' },
  { value: 'health_systems_research', label: 'Health Systems Research' },
  { value: 'health_policy_research', label: 'Health Policy Research' },
  { value: 'health_services_research', label: 'Health Services Research' },
  { value: 'implementation_science', label: 'Implementation Science' },
  { value: 'knowledge_translation', label: 'Knowledge Translation' },
  { value: 'evidence_based_practice', label: 'Evidence-Based Practice' },
  { value: 'health_technology_assessment', label: 'Health Technology Assessment' },
  { value: 'cost_effectiveness_analysis', label: 'Cost-Effectiveness Analysis' },
  { value: 'health_economic_evaluation', label: 'Health Economic Evaluation' },
  { value: 'healthcare_delivery_models', label: 'Healthcare Delivery Models' },
  { value: 'integrated_care', label: 'Integrated Care' },
  { value: 'coordinated_care', label: 'Coordinated Care' },
  { value: 'chronic_disease_management', label: 'Chronic Disease Management' },
  { value: 'population_health', label: 'Population Health' },
  { value: 'community_health_assessment', label: 'Community Health Assessment' },
  { value: 'health_surveillance', label: 'Health Surveillance' },
  { value: 'disease_surveillance', label: 'Disease Surveillance' },
  { value: 'outbreak_response', label: 'Outbreak Response' },
  { value: 'global_health_security', label: 'Global Health Security' },
  { value: 'biosecurity', label: 'Biosecurity' },
  { value: 'biodefense', label: 'Biodefense' },
  { value: 'emergency_preparedness', label: 'Emergency Preparedness' },
  { value: 'crisis_response', label: 'Crisis Response' },
  { value: 'disaster_response', label: 'Disaster Response' },
  { value: 'humanitarian_logistics', label: 'Humanitarian Logistics' },
  { value: 'relief_operations', label: 'Relief Operations' },
  { value: 'shelter_programs', label: 'Shelter Programs' },
  { value: 'food_aid', label: 'Food Aid' },
  { value: 'nutrition_support', label: 'Nutrition Support' },
  { value: 'cash_transfers', label: 'Cash Transfers' },
  { value: 'voucher_programs', label: 'Voucher Programs' },
  { value: 'livelihood_support', label: 'Livelihood Support' },
  { value: 'economic_recovery', label: 'Economic Recovery' },
  { value: 'post_conflict_reconstruction', label: 'Post-Conflict Reconstruction' },
  { value: 'state_building', label: 'State Building' },
  { value: 'governance_reform', label: 'Governance Reform' },
  { value: 'electoral_support', label: 'Electoral Support' },
  { value: 'democracy_promotion', label: 'Democracy Promotion' },
  { value: 'civic_participation', label: 'Civic Participation' },
  { value: 'voter_education', label: 'Voter Education' },
  { value: 'political_participation', label: 'Political Participation' },
  { value: 'women_in_politics', label: 'Women in Politics' },
  { value: 'youth_in_politics', label: 'Youth in Politics' },
  { value: 'minority_representation', label: 'Minority Representation' },
  { value: 'indigenous_representation', label: 'Indigenous Representation' },
  { value: 'disability_representation', label: 'Disability Representation' },
  { value: 'lgbtq_representation', label: 'LGBTQ+ Representation' },
  { value: 'inclusive_governance', label: 'Inclusive Governance' },
  { value: 'public_sector_reform', label: 'Public Sector Reform' },
  { value: 'civil_service_reform', label: 'Civil Service Reform' },
  { value: 'judicial_reform', label: 'Judicial Reform' },
  { value: 'legal_reform', label: 'Legal Reform' },
  { value: 'constitutional_reform', label: 'Constitutional Reform' },
  { value: 'human_rights_law', label: 'Human Rights Law' },
  { value: 'international_law', label: 'International Law' },
  { value: 'humanitarian_law', label: 'Humanitarian Law' },
  { value: 'environmental_law', label: 'Environmental Law' },
  { value: 'labor_law', label: 'Labor Law' },
  { value: 'trade_law', label: 'Trade Law' },
  { value: 'intellectual_property_law', label: 'Intellectual Property Law' },
  { value: 'cyber_law', label: 'Cyber Law' },
  { value: 'data_protection', label: 'Data Protection' },
  { value: 'privacy_rights', label: 'Privacy Rights' },
  { value: 'digital_rights', label: 'Digital Rights' },
  { value: 'internet_freedom', label: 'Internet Freedom' },
  { value: 'cybersecurity_policy', label: 'Cybersecurity Policy' },
  { value: 'technology_governance', label: 'Technology Governance' },
  { value: 'ai_governance', label: 'AI Governance' },
  { value: 'ethical_ai', label: 'Ethical AI' },
  { value: 'ai_for_good', label: 'AI for Good' },
  { value: 'ai_in_healthcare', label: 'AI in Healthcare' },
  { value: 'ai_in_education', label: 'AI in Education' },
  { value: 'ai_in_agriculture', label: 'AI in Agriculture' },
  { value: 'ai_in_climate', label: 'AI in Climate' },
  { value: 'ai_in_governance', label: 'AI in Governance' },
  { value: 'ai_in_justice', label: 'AI in Justice' },
  { value: 'ai_in_transportation', label: 'AI in Transportation' },
  { value: 'ai_in_energy', label: 'AI in Energy' },
  { value: 'ai_in_finance', label: 'AI in Finance' },
  { value: 'ai_in_manufacturing', label: 'AI in Manufacturing' },
  { value: 'ai_in_retail', label: 'AI in Retail' },
  { value: 'ai_in_logistics', label: 'AI in Logistics' },
  { value: 'ai_in_security', label: 'AI in Security' },
  { value: 'ai_in_disaster_response', label: 'AI in Disaster Response' },
  { value: 'ai_in_humanitarian_aid', label: 'AI in Humanitarian Aid' },
  { value: 'ai_in_development', label: 'AI in Development' },
  { value: 'ai_in_research', label: 'AI in Research' },
  { value: 'machine_learning_research', label: 'Machine Learning Research' },
  { value: 'deep_learning', label: 'Deep Learning' },
  { value: 'natural_language_processing', label: 'Natural Language Processing' },
  { value: 'computer_vision', label: 'Computer Vision' },
  { value: 'reinforcement_learning', label: 'Reinforcement Learning' },
  { value: 'data_mining', label: 'Data Mining' },
  { value: 'predictive_analytics', label: 'Predictive Analytics' },
  { value: 'business_intelligence', label: 'Business Intelligence' },
  { value: 'data_visualization', label: 'Data Visualization' },
  { value: 'data_governance', label: 'Data Governance' },
  { value: 'data_ethics', label: 'Data Ethics' },
  { value: 'data_privacy', label: 'Data Privacy' },
  { value: 'data_security', label: 'Data Security' },
  { value: 'cloud_computing', label: 'Cloud Computing' },
  { value: 'edge_computing', label: 'Edge Computing' },
  { value: 'blockchain_research', label: 'Blockchain Research' },
  { value: 'cryptocurrency', label: 'Cryptocurrency' },
  { value: 'decentralized_finance', label: 'Decentralized Finance' },
  { value: 'smart_contracts', label: 'Smart Contracts' },
  { value: 'blockchain_in_supply_chain', label: 'Blockchain in Supply Chain' },
  { value: 'blockchain_in_healthcare', label: 'Blockchain in Healthcare' },
  { value: 'blockchain_in_education', label: 'Blockchain in Education' },
  { value: 'blockchain_in_governance', label: 'Blockchain in Governance' },
  { value: 'blockchain_in_finance', label: 'Blockchain in Finance' },
  { value: 'blockchain_in_agriculture', label: 'Blockchain in Agriculture' },
  { value: 'blockchain_in_energy', label: 'Blockchain in Energy' },
  { value: 'blockchain_in_logistics', label: 'Blockchain in Logistics' },
  { value: 'blockchain_in_real_estate', label: 'Blockchain in Real Estate' },
  { value: 'blockchain_in_voting', label: 'Blockchain in Voting' },
  { value: 'blockchain_in_identity', label: 'Blockchain in Identity' },
  { value: 'digital_identity', label: 'Digital Identity' },
  { value: 'identity_management', label: 'Identity Management' },
  { value: 'biometric_technology', label: 'Biometric Technology' },
  { value: 'cybersecurity_research', label: 'Cybersecurity Research' },
  { value: 'network_security', label: 'Network Security' },
  { value: 'application_security', label: 'Application Security' },
  { value: 'endpoint_security', label: 'Endpoint Security' },
  { value: 'cloud_security', label: 'Cloud Security' },
  { value: 'iot_security', label: 'IoT Security' },
  { value: 'cyber_threat_intelligence', label: 'Cyber Threat Intelligence' },
  { value: 'incident_response', label: 'Incident Response' },
  { value: 'penetration_testing', label: 'Penetration Testing' },
  { value: 'ethical_hacking', label: 'Ethical Hacking' },
  { value: 'cybersecurity_training', label: 'Cybersecurity Training' },
  { value: 'cybersecurity_policy', label: 'Cybersecurity Policy' },
  { value: 'cybercrime_prevention', label: 'Cybercrime Prevention' },
  { value: 'digital_forensics', label: 'Digital Forensics' },
  { value: 'cryptography', label: 'Cryptography' },
  { value: 'secure_software_development', label: 'Secure Software Development' },
  { value: 'devsecops', label: 'DevSecOps' },
  { value: 'software_engineering', label: 'Software Engineering' },
  { value: 'agile_development', label: 'Agile Development' },
  { value: 'devops', label: 'DevOps' },
  { value: 'full_stack_development', label: 'Full Stack Development' },
  { value: 'frontend_development', label: 'Frontend Development' },
  { value: 'backend_development', label: 'Backend Development' },
  { value: 'mobile_app_development', label: 'Mobile App Development' },
  { value: 'web_development', label: 'Web Development' },
  { value: 'game_development', label: 'Game Development' },
  { value: 'virtual_reality', label: 'Virtual Reality' },
  { value: 'augmented_reality', label: 'Augmented Reality' },
  { value: 'mixed_reality', label: 'Mixed Reality' },
  { value: 'metaverse', label: 'Metaverse' },
  { value: '3d_modeling', label: '3D Modeling' },
  { value: 'animation', label: 'Animation' },
  { value: 'graphic_design', label: 'Graphic Design' },
  { value: 'ui_ux_design', label: 'UI/UX Design' },
  { value: 'product_design', label: 'Product Design' },
  { value: 'industrial_design', label: 'Industrial Design' },
  { value: 'fashion_design', label: 'Fashion Design' },
  { value: 'sustainable_fashion', label: 'Sustainable Fashion' },
  { value: 'textile_innovation', label: 'Textile Innovation' },
  { value: 'wearable_technology', label: 'Wearable Technology' },
  { value: 'smart_textiles', label: 'Smart Textiles' },
  { value: 'material_science', label: 'Material Science' },
  { value: 'nanotechnology', label: 'Nanotechnology' },
  { value: 'biomaterials', label: 'Biomaterials' },
  { value: 'synthetic_biology', label: 'Synthetic Biology' },
  { value: 'bioengineering', label: 'Bioengineering' },
  { value: 'tissue_engineering', label: 'Tissue Engineering' },
  { value: 'regenerative_medicine', label: 'Regenerative Medicine' },
  { value: 'gene_therapy', label: 'Gene Therapy' },
  { value: 'crispr_technology', label: 'CRISPR Technology' },
  { value: 'genomics', label: 'Genomics' },
  { value: 'proteomics', label: 'Proteomics' },
  { value: 'bioinformatics', label: 'Bioinformatics' },
  { value: 'computational_biology', label: 'Computational Biology' },
  { value: 'systems_biology', label: 'Systems Biology' },
  { value: 'microbiology', label: 'Microbiology' },
  { value: 'virology', label: 'Virology' },
  { value: 'immunology', label: 'Immunology' },
  { value: 'neuroscience', label: 'Neuroscience' },
  { value: 'neurotechnology', label: 'Neurotechnology' },
  { value: 'brain_computer_interface', label: 'Brain-Computer Interface' },
  { value: 'cognitive_science', label: 'Cognitive Science' },
  { value: 'psychology_research', label: 'Psychology Research' },
  { value: 'behavioral_science', label: 'Behavioral Science' },
  { value: 'social_psychology', label: 'Social Psychology' },
  { value: 'clinical_psychology', label: 'Clinical Psychology' },
  { value: 'counseling_psychology', label: 'Counseling Psychology' },
  { value: 'mental_health_research', label: 'Mental Health Research' },
  { value: 'psychiatric_research', label: 'Psychiatric Research' },
  { value: 'addiction_research', label: 'Addiction Research' },
  { value: 'trauma_research', label: 'Trauma Research' },
  { value: 'ptsd_research', label: 'PTSD Research' },
  { value: 'anxiety_research', label: 'Anxiety Research' },
  { value: 'depression_research', label: 'Depression Research' },
  { value: 'suicide_prevention', label: 'Suicide Prevention' },
  { value: 'mental_health_stigma', label: 'Mental Health Stigma' },
  { value: 'mental_health_advocacy', label: 'Mental Health Advocacy' },
  { value: 'community_mental_health', label: 'Community Mental Health' },
  { value: 'telepsychiatry', label: 'Telepsychiatry' },
  { value: 'digital_mental_health', label: 'Digital Mental Health' },
  { value: 'mental_health_apps', label: 'Mental Health Apps' },
  { value: 'wellness_programs', label: 'Wellness Programs' },
  { value: 'mindfulness', label: 'Mindfulness' },
  { value: 'meditation', label: 'Meditation' },
  { value: 'yoga', label: 'Yoga' },
  { value: 'holistic_health', label: 'Holistic Health' },
  { value: 'alternative_medicine', label: 'Alternative Medicine' },
  { value: 'complementary_medicine', label: 'Complementary Medicine' },
  { value: 'integrative_medicine', label: 'Integrative Medicine' },
  { value: 'traditional_medicine', label: 'Traditional Medicine' },
  { value: 'herbal_medicine', label: 'Herbal Medicine' },
  { value: 'ayurveda', label: 'Ayurveda' },
  { value: 'chinese_medicine', label: 'Chinese Medicine' },
  { value: 'acupuncture', label: 'Acupuncture' },
  { value: 'homeopathy', label: 'Homeopathy' },
  { value: 'naturopathy', label: 'Naturopathy' },
  { value: 'chiropractic', label: 'Chiropractic' },
  { value: 'physical_therapy', label: 'Physical Therapy' },
  { value: 'occupational_therapy', label: 'Occupational Therapy' },
  { value: 'speech_therapy', label: 'Speech Therapy' },
  { value: 'rehabilitation_medicine', label: 'Rehabilitation Medicine' },
  { value: 'sports_medicine', label: 'Sports Medicine' },
  { value: 'exercise_science', label: 'Exercise Science' },
  { value: 'physical_fitness', label: 'Physical Fitness' },
  { value: 'sports_training', label: 'Sports Training' },
  { value: 'youth_sports', label: 'Youth Sports' },
  { value: 'community_sports', label: 'Community Sports' },
  { value: 'sports_for_development', label: 'Sports for Development' },
  { value: 'sports_diplomacy', label: 'Sports Diplomacy' },
  { value: 'sports_inclusion', label: 'Sports Inclusion' },
  { value: 'adaptive_sports', label: 'Adaptive Sports' },
  { value: 'paralympic_sports', label: 'Paralympic Sports' },
  { value: 'special_olympics', label: 'Special Olympics' },
  { value: 'sports_psychology', label: 'Sports Psychology' },
  { value: 'sports_nutrition', label: 'Sports Nutrition' },
  { value: 'sports_technology', label: 'Sports Technology' },
  { value: 'wearable_sports_tech', label: 'Wearable Sports Tech' },
  { value: 'sports_analytics', label: 'Sports Analytics' },
  { value: 'esports', label: 'Esports' },
  { value: 'gaming_industry', label: 'Gaming Industry' },
  { value: 'game_design', label: 'Game Design' },
  { value: 'serious_games', label: 'Serious Games' },
  { value: 'gamification', label: 'Gamification' },
  { value: 'educational_games', label: 'Educational Games' },
  { value: 'health_games', label: 'Health Games' },
  { value: 'social_impact_games', label: 'Social Impact Games' },
  { value: 'virtual_learning', label: 'Virtual Learning' },
  { value: 'e_learning', label: 'E-Learning' },
  { value: 'learning_management_systems', label: 'Learning Management Systems' },
  { value: 'educational_innovation', label: 'Educational Innovation' },
  { value: 'pedagogical_research', label: 'Pedagogical Research' },
  { value: 'learning_sciences', label: 'Learning Sciences' },
  { value: 'educational_psychology', label: 'Educational Psychology' },
  { value: 'student_engagement', label: 'Student Engagement' },
  { value: 'active_learning', label: 'Active Learning' },
  { value: 'project_based_learning', label: 'Project-Based Learning' },
  { value: 'inquiry_based_learning', label: 'Inquiry-Based Learning' },
  { value: 'experiential_learning', label: 'Experiential Learning' },
  { value: 'service_learning', label: 'Service Learning' },
  { value: 'community_service', label: 'Community Service' },
  { value: 'volunteer_programs', label: 'Volunteer Programs' },
  { value: 'corporate_volunteering', label: 'Corporate Volunteering' },
  { value: 'global_volunteering', label: 'Global Volunteering' },
  { value: 'youth_volunteering', label: 'Youth Volunteering' },
  { value: 'senior_volunteering', label: 'Senior Volunteering' },
  { value: 'virtual_volunteering', label: 'Virtual Volunteering' },
  { value: 'nonprofit_management', label: 'Nonprofit Management' },
  { value: 'fundraising', label: 'Fundraising' },
  { value: 'grant_writing', label: 'Grant Writing' },
  { value: 'donor_relations', label: 'Donor Relations' },
  { value: 'philanthropic_advisory', label: 'Philanthropic Advisory' },
  { value: 'charitable_giving', label: 'Charitable Giving' },
  { value: 'legacy_giving', label: 'Legacy Giving' },
  { value: 'endowment_funds', label: 'Endowment Funds' },
  { value: 'foundation_management', label: 'Foundation Management' },
  { value: 'social_impact_funds', label: 'Social Impact Funds' },
  { value: 'impact_philanthropy', label: 'Impact Philanthropy' },
  { value: 'strategic_philanthropy', label: 'Strategic Philanthropy' },
  { value: 'collaborative_philanthropy', label: 'Collaborative Philanthropy' },
  { value: 'community_foundations', label: 'Community Foundations' },
  { value: 'corporate_foundations', label: 'Corporate Foundations' },
  { value: 'family_foundations', label: 'Family Foundations' },
  { value: 'private_foundations', label: 'Private Foundations' },
  { value: 'public_foundations', label: 'Public Foundations' },
  { value: 'grantmaking', label: 'Grantmaking' },
  { value: 'program_evaluation', label: 'Program Evaluation' },
  { value: 'outcome_measurement', label: 'Outcome Measurement' },
  { value: 'social_return_on_investment', label: 'Social Return on Investment' },
  { value: 'impact_metrics', label: 'Impact Metrics' },
  { value: 'performance_management', label: 'Performance Management' },
  { value: 'organizational_development', label: 'Organizational Development' },
  { value: 'leadership_development', label: 'Leadership Development' },
  { value: 'team_building', label: 'Team Building' },
  { value: 'change_management', label: 'Change Management' },
  { value: 'strategic_planning', label: 'Strategic Planning' },
  { value: 'business_strategy', label: 'Business Strategy' },
  { value: 'social_business', label: 'Social Business' },
  { value: 'b_corp', label: 'B Corp' },
  { value: 'sustainable_business', label: 'Sustainable Business' },
  { value: 'corporate_sustainability', label: 'Corporate Sustainability' },
  { value: 'shared_value', label: 'Shared Value' },
  { value: 'stakeholder_engagement', label: 'Stakeholder Engagement' },
  { value: 'community_relations', label: 'Community Relations' },
  { value: 'public_relations', label: 'Public Relations' },
  { value: 'crisis_communications', label: 'Crisis Communications' },
  { value: 'media_relations', label: 'Media Relations' },
  { value: 'digital_marketing', label: 'Digital Marketing' },
  { value: 'social_media_marketing', label: 'Social Media Marketing' },
  { value: 'content_marketing', label: 'Content Marketing' },
  { value: 'brand_management', label: 'Brand Management' },
  { value: 'storytelling', label: 'Storytelling' },
  { value: 'advocacy_campaigns', label: 'Advocacy Campaigns' },
  { value: 'public_awareness', label: 'Public Awareness' },
  { value: 'behavior_change', label: 'Behavior Change' },
  { value: 'social_marketing', label: 'Social Marketing' },
  { value: 'health_communications', label: 'Health Communications' },
  { value: 'environmental_communications', label: 'Environmental Communications' },
  { value: 'science_communications', label: 'Science Communications' },
  { value: 'public_engagement', label: 'Public Engagement' },
  { value: 'citizen_science', label: 'Citizen Science' },
  { value: 'community_science', label: 'Community Science' },
  { value: 'open_science', label: 'Open Science' },
  { value: 'research_dissemination', label: 'Research Dissemination' },
  { value: 'knowledge_mobilization', label: 'Knowledge Mobilization' },
  { value: 'policy_briefing', label: 'Policy Briefing' },
  { value: 'thought_leadership', label: 'Thought Leadership' },
  { value: 'public_speaking', label: 'Public Speaking' },
  { value: 'conference_organization', label: 'Conference Organization' },
  { value: 'event_management', label: 'Event Management' },
  { value: 'webinar_series', label: 'Webinar Series' },
  { value: 'virtual_conferences', label: 'Virtual Conferences' },
  { value: 'hybrid_events', label: 'Hybrid Events' },
  { value: 'professional_conferences', label: 'Professional Conferences' },
  { value: 'academic_conferences', label: 'Academic Conferences' },
  { value: 'industry_conferences', label: 'Industry Conferences' },
  { value: 'summits', label: 'Summits' },
  { value: 'roundtables', label: 'Roundtables' },
  { value: 'panel_discussions', label: 'Panel Discussions' },
  { value: 'keynote_speaking', label: 'Keynote Speaking' },
  { value: 'poster_presentations', label: 'Poster Presentations' },
  { value: 'research_symposia', label: 'Research Symposia' },
  { value: 'innovation_forums', label: 'Innovation Forums' },
  { value: 'policy_forums', label: 'Policy Forums' },
  { value: 'stakeholder_forums', label: 'Stakeholder Forums' },
  { value: 'community_forums', label: 'Community Forums' },
  { value: 'town_hall_meetings', label: 'Town Hall Meetings' },
  { value: 'public_consultations', label: 'Public Consultations' },
  { value: 'focus_groups', label: 'Focus Groups' },
  { value: 'participatory_workshops', label: 'Participatory Workshops' },
  { value: 'capacity_building_workshops', label: 'Capacity Building Workshops' },
  { value: 'skills_workshops', label: 'Skills Workshops' },
  { value: 'technical_workshops', label: 'Technical Workshops' },
  { value: 'leadership_workshops', label: 'Leadership Workshops' },
  { value: 'entrepreneurship_workshops', label: 'Entrepreneurship Workshops' },
  { value: 'innovation_workshops', label: 'Innovation Workshops' },
  { value: 'design_workshops', label: 'Design Workshops' },
  { value: 'co_design', label: 'Co-Design' },
  { value: 'participatory_design', label: 'Participatory Design' },
  { value: 'human_centered_design', label: 'Human-Centered Design' },
  { value: 'service_design', label: 'Service Design' },
  { value: 'systems_design', label: 'Systems Design' },
  { value: 'social_design', label: 'Social Design' },
  { value: 'inclusive_design', label: 'Inclusive Design' },
  { value: 'accessible_design', label: 'Accessible Design' },
  { value: 'universal_access', label: 'Universal Access' },
  { value: 'equity_centered_design', label: 'Equity-Centered Design' },
  { value: 'community_based_design', label: 'Community-Based Design' },
  { value: 'cultural_design', label: 'Cultural Design' },
  { value: 'indigenous_design', label: 'Indigenous Design' },
  { value: 'sustainable_product_design', label: 'Sustainable Product Design' },
  { value: 'green_product_design', label: 'Green Product Design' },
  { value: 'eco_design', label: 'Eco-Design' },
  { value: 'cradle_to_cradle', label: 'Cradle to Cradle' },
  { value: 'life_cycle_assessment', label: 'Life Cycle Assessment' },
  { value: 'product_sustainability', label: 'Product Sustainability' },
  { value: 'sustainable_innovation', label: 'Sustainable Innovation' },
  { value: 'green_innovation', label: 'Green Innovation' },
  { value: 'climate_innovation', label: 'Climate Innovation' },
  { value: 'social_innovation_research', label: 'Social Innovation Research' },
  { value: 'open_innovation', label: 'Open Innovation' },
  { value: 'collaborative_innovation', label: 'Collaborative Innovation' },
  { value: 'frugal_innovation', label: 'Frugal Innovation' },
  { value: 'disruptive_innovation', label: 'Disruptive Innovation' },
  { value: 'incremental_innovation', label: 'Incremental Innovation' },
  { value: 'radical_innovation', label: 'Radical Innovation' },
  { value: 'technology_innovation', label: 'Technology Innovation' },
  { value: 'business_model_innovation', label: 'Business Model Innovation' },
  { value: 'service_innovation', label: 'Service Innovation' },
  { value: 'process_innovation', label: 'Process Innovation' },
  { value: 'organizational_innovation', label: 'Organizational Innovation' },
  { value: 'policy_innovation', label: 'Policy Innovation' },
  { value: 'governance_innovation', label: 'Governance Innovation' },
  { value: 'systemic_innovation', label: 'Systemic Innovation' },
  { value: 'transformative_innovation', label: 'Transformative Innovation' },
  { value: 'innovation_ecosystems', label: 'Innovation Ecosystems' },
  { value: 'innovation_policy', label: 'Innovation Policy' },
  { value: 'research_and_development', label: 'Research and Development' },
  { value: 'applied_research', label: 'Applied Research' },
  { value: 'basic_research', label: 'Basic Research' },
  { value: 'translational_research', label: 'Translational Research' },
  { value: 'experimental_research', label: 'Experimental Research' },
  { value: 'qualitative_research', label: 'Qualitative Research' },
  { value: 'quantitative_research', label: 'Quantitative Research' },
  { value: 'mixed_methods_research', label: 'Mixed Methods Research' },
  { value: 'participatory_research', label: 'Participatory Research' },
  { value: 'ethnographic_research', label: 'Ethnographic Research' },
  { value: 'case_study_research', label: 'Case Study Research' },
  { value: 'longitudinal_research', label: 'Longitudinal Research' },
  { value: 'cross_sectional_research', label: 'Cross-Sectional Research' },
  { value: 'survey_research', label: 'Survey Research' },
  { value: 'field_research', label: 'Field Research' },
  { value: 'laboratory_research', label: 'Laboratory Research' },
  { value: 'clinical_research', label: 'Clinical Research' },
  { value: 'observational_research', label: 'Observational Research' },
  { value: 'experimental_design', label: 'Experimental Design' },
  { value: 'research_methodology', label: 'Research Methodology' },
  { value: 'data_management', label: 'Data Management' },
  { value: 'research_data_management', label: 'Research Data Management' },
  { value: 'open_research', label: 'Open Research' },
  { value: 'reproducible_research', label: 'Reproducible Research' },
  { value: 'research_integrity', label: 'Research Integrity' },
  { value: 'peer_review', label: 'Peer Review' },
  { value: 'academic_publishing', label: 'Academic Publishing' },
  { value: 'open_access_publishing', label: 'Open Access Publishing' },
  { value: 'scholarly_communication', label: 'Scholarly Communication' },
  { value: 'research_impact', label: 'Research Impact' },
  { value: 'research_evaluation', label: 'Research Evaluation' },
  { value: 'bibliometrics', label: 'Bibliometrics' },
  { value: 'altmetrics', label: 'Altmetrics' },
  { value: 'research_funding', label: 'Research Funding' },
  { value: 'research_grants', label: 'Research Grants' },
  { value: 'research_fellowships', label: 'Research Fellowships' },
  { value: 'research_scholarships', label: 'Research Scholarships' },
  { value: 'research_collaboration', label: 'Research Collaboration' },
];